### ISSUE TITLE
model/train/train.py is not macOS (gpu - mps) aware

### ISSUE THREAD

**Issue by petergreis** [hf-lin/ChatMusician#10]
Running

`./model/train/scripts/train.sh datasets m-a-p/ChatMusician-Base` as per the README

exits with:  

```
(ml) petergreis@MacBook-Pro-M1-Max-2021 ChatMusician % ./model/train/scripts/train.sh datasets m-a-p/ChatMusician-Base
[2024-03-29 21:11:10,773] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to mps (auto detect)
[2024-03-29 21:11:12,870] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-03-29 21:11:14,403] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-03-29 21:11:14,404] [INFO] [runner.py:568:main] cmd = /Users/petergreis/anaconda3/envs/ml/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None model/train/train.py --train_path datasets --model_name_or_path m-a-p/ChatMusician-Base --per_device_train_batch_size 1 --max_len 2048 --max_src_len 1536 --num_train_epochs 2 --gradient_accumulation_steps 1 --learning_rate 1e-4 --weight_decay 0.1 --warmup_ratio 0.1 --mode llama --train_type lora --lora_dim 64 --lora_alpha 16 --lora_dropout 0.1 --lora_module_name q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj --seed 1234 --save_model_step 2000 --ds_file model/train/config/ds_zero2_no_offload.json --show_loss_step 50 --output_dir model/train/output_dir
[2024-03-29 21:11:15,592] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to mps (auto detect)
[2024-03-29 21:11:15,801] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-03-29 21:11:16,405] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2024-03-29 21:11:16,405] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2024-03-29 21:11:16,405] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2024-03-29 21:11:16,405] [INFO] [launch.py:163:main] dist_world_size=1
[2024-03-29 21:11:16,405] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
[2024-03-29 21:11:17,605] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to mps (auto detect)
[2024-03-29 21:11:17,821] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "/Users/petergreis/Library/CloudStorage/Dropbox/Leeds/Project/ChatMusician/model/train/train.py", line 252, in <module>
    main()
  File "/Users/petergreis/Library/CloudStorage/Dropbox/Leeds/Project/ChatMusician/model/train/train.py", line 70, in main
    torch.cuda.set_device(args.local_rank)
  File "/Users/petergreis/anaconda3/envs/ml/lib/python3.11/site-packages/torch/cuda/__init__.py", line 404, in set_device
    torch._C._cuda_setDevice(device)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
[2024-03-29 21:11:20,433] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 7216
[2024-03-29 21:11:20,436] [ERROR] [launch.py:321:sigkill_handler] ['/Users/petergreis/anaconda3/envs/ml/bin/python', '-u', 'model/train/train.py', '--local_rank=0', '--train_path', 'datasets', '--model_name_or_path', 'm-a-p/ChatMusician-Base', '--per_device_train_batch_size', '1', '--max_len', '2048', '--max_src_len', '1536', '--num_train_epochs', '2', '--gradient_accumulation_steps', '1', '--learning_rate', '1e-4', '--weight_decay', '0.1', '--warmup_ratio', '0.1', '--mode', 'llama', '--train_type', 'lora', '--lora_dim', '64', '--lora_alpha', '16', '--lora_dropout', '0.1', '--lora_module_name', 'q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj', '--seed', '1234', '--save_model_step', '2000', '--ds_file', 'model/train/config/ds_zero2_no_offload.json', '--show_loss_step', '50', '--output_dir', 'model/train/output_dir'] exits with return code = 1
```

How should the call to

`mps_available = mps.is_available()`

be incorporated into the code at line 70 to set the device to "mps"?

**Comment by hf-lin** [comment]
Sorry we haven't trained a model on a mac.
Maybe modify line 70 to:
`        device = torch.device("mps")
`
would be helpful.
