### ISSUE TITLE
After update to data_preprocess.py, where is the training data?

### ISSUE THREAD

**Issue by petergreis** [hf-lin/ChatMusician#11]
When attempting to train (as per the readme), the shell script file expands to:

`model/train/train.py --train_path datasets --model_name_or_path m-a-p/ChatMusician-Base --per_device_train_batch_size 1 --max_len 2048 --max_src_len 1536 --num_train_epochs 2 --gradient_accumulation_steps 1 --learning_rate 1e-4 --weight_decay 0.1 --warmup_ratio 0.1 --mode llama --train_type lora --lora_dim 64 --lora_alpha 16 --lora_dropout 0.1 --lora_module_name q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj --seed 1234 --save_model_step 2000 --show_loss_step 50 --output_dir model/train/output_dir`

Which then throws this trace:

```
Traceback (most recent call last):
  File "/Users/petergreis/Library/CloudStorage/Dropbox/Leeds/Project/ChatMusician/model/train/train.py", line 129, in <module>
    main()
  File "/Users/petergreis/Library/CloudStorage/Dropbox/Leeds/Project/ChatMusician/model/train/train.py", line 89, in main
    tokenizer = MODE[args.mode]["tokenizer"].from_pretrained(args.model_name_or_path, use_fast=False, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petergreis/anaconda3/envs/ml/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2029, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petergreis/anaconda3/envs/ml/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2261, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petergreis/Library/CloudStorage/Dropbox/Leeds/Project/ChatMusician/model/train/llama/tokenization_llama.py", line 79, in __init__
    super().__init__(
  File "/Users/petergreis/anaconda3/envs/ml/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 367, in __init__
    self._add_tokens(
  File "/Users/petergreis/anaconda3/envs/ml/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
    current_vocab = self.get_vocab().copy()
                    ^^^^^^^^^^^^^^^^
  File "/Users/petergreis/Library/CloudStorage/Dropbox/Leeds/Project/ChatMusician/model/train/llama/tokenization_llama.py", line 113, in get_vocab
    vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
                                                             ^^^^^^^^^^^^^^^
  File "/Users/petergreis/Library/CloudStorage/Dropbox/Leeds/Project/ChatMusician/model/train/llama/tokenization_llama.py", line 109, in vocab_size
    return self.sp_model.get_piece_size()
           ^^^^^^^^^^^^^
AttributeError: 'LlamaTokenizer' object has no attribute 'sp_model'
```

...which would seem to indicate that the training data is not found. The recent changes to data_preprocess.py creates datasets/processed_tokens and datasets/processed_tokens_text. Although adjusting `--train_path datasets` to either of the previous, it would seem that the tokenised data is not found. Any suggestions?

**Comment by hf-lin** [comment]
The dataset path is not the cause of this problem. It is the transformers version. 
Same issue: [Failed to load with transformers>=4.34](https://github.com/baichuan-inc/Baichuan2/issues/226)
