### ISSUE TITLE
Running out of GPU memory in Google colab; ideas?

### ISSUE THREAD

**Issue by petergreis** [hf-lin/ChatMusician#13]
Currently seeing this when attempting to train in Google colab on a T4 GPU. Any idea how I can further reduce the footprint to make this run?

`2024-04-03 14:35:22,511] [INFO] [utils.py:808:see_memory_usage] CPU Virtual Memory:  used = 3.85 GB, percent = 7.6%
Traceback (most recent call last):
  File "/content/drive/MyDrive/project/ChatMusician/model/train/train.py", line 254, in <module>
    main()
  File "/content/drive/MyDrive/project/ChatMusician/model/train/train.py", line 198, in main
    model, optimizer, _, lr_scheduler = deepspeed.initialize(model=model, args=args, config=ds_config,
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 176, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1256, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1513, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 535, in __init__
    self.initialize_optimizer_states()
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 670, in initialize_optimizer_states
    single_grad_partition = torch.zeros(int(self.partition_size[i]),
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 610.00 MiB. GPU 0 has a total capacity of 14.75 GiB of which 403.06 MiB is free. Process 129704 has 14.35 GiB memory in use. Of the allocated memory 13.48 GiB is allocated by PyTorch, and 197.48 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2024-04-03 14:35:26,240] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 9908
[2024-04-03 14:35:26,240] [ERROR] [launch.py:322:sigkill_handler] ['/usr/bin/python3', '-u', 'model/train/train.py', '--local_rank=0', '--train_path', 'datasets/train_bias_sample_100', '--model_name_or_path', 'm-a-p/ChatMusician-Base', '--per_device_train_batch_size', '1', '--max_len', '2048', '--max_src_len', '1536', '--num_train_epochs', '2', '--gradient_accumulation_steps', '4', '--learning_rate', '1e-4', '--weight_decay', '0.1', '--warmup_ratio', '0.1', '--mode', 'llama', '--train_type', 'lora', '--lora_dim', '64', '--lora_alpha', '16', '--lora_dropout', '0.1', '--lora_module_name', 'q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj', '--seed', '1234', '--save_model_step', '2000', '--ds_file', 'model/train/config/ds_zero2_no_offload.json', '--show_loss_step', '50', '--output_dir', 'model/train/output_dir'] exits with return code = 1`

**Comment by hf-lin** [comment]
T4(GPU memory 16GB) is not sufficient for finetuning a 7B model in fp16 precision.

My advices:
1. You can reduce most of the trainable parameters of LoRa. 
2. Use lower precision such as 8bit for training.
3. Enable ZeRO-3 offload, but it's time consuming.

[Huggingface Efficient Training Techniques](https://huggingface.co/docs/transformers/v4.39.3/perf_train_gpu_one) could be useful to you.

**Comment by petergreis** [comment]
OK, I have a solution. Digital Ocean Paperspace has A6000 GPU resources which give roughly 45GB of space on the GPU. For training so far this is working. Thanks again for your feedback!
